name: Simple Local

on:
  push:

jobs:
  build-node:
    runs-on: ubuntu-latest

    container:
      image: node:18
      options: --user root

    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v3

      - name: Verificar Versão do Node.js
        run: node --version

      - name: Verificar Versão do NPM
        run: npm --version

      - name: Instalar Dependências
        run: npm install

      - name: Instalar Moment.js
        run: npm install --save moment

      - name: Executar Aplicação
        run: node app.js
