name: Simple Local

on:
  push:

jobs:
  build-node:
    runs-on: ubuntu-latest

    container:
      image: node:18
      options: --user root

    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v3

      - name: Run node --version
        run: node --version

      - name: Run npm --version
        run: npm --version

      - name: Run npm install
        run: npm install

      - name: Run npm install --save moment
        run: npm install --save moment

      - name: Run node app.js
        run: node app.js
